use G1_Car_Insurance;

/*    First Query    */
SELECT DISTINCT G1_CUSTOMER.* FROM G1_CUSTOMER INNER JOIN G1_VEHICLE ON 
G1_VEHICLE.G1_CUST_ID = G1_CUSTOMER.G1_CUST_ID WHERE 
G1_CUSTOMER.G1_CUST_ID IN (SELECT G1_CUST_ID FROM G1_INCIDENT_REPORT) 
AND G1_CUSTOMER.G1_CUST_ID IN (SELECT G1_CUST_ID FROM G1_CLAIM 
WHERE G1_CLAIM_STATUS = 'pending');

/*   Second Query   */
SELECT G1_CUSTOMER.* FROM G1_CUSTOMER WHERE G1_CUST_ID IN 
(SELECT G1_CUST_ID FROM G1_PREMIUM WHERE G1_PREMIUM_PAYMENT_AMOUNT >
(SELECT SUM(G1_CUST_ID) FROM G1_CUSTOMER ));

/*   Third Query    */
SELECT C.G1_COMPANY_NAME FROM G1_COMPANY C INNER JOIN G1_PRODUCT P ON 
P.G1_COMPANY_NAME = C.G1_COMPANY_NAME GROUP BY P.G1_COMPANY_NAME HAVING COUNT(*) > 
ALL (SELECT COUNT(*) FROM G1_COMPANY GROUP BY G1_COMPANY_NAME HAVING 
COUNT(G1_COMPANY_LOCATION)>1);

/*   Fourth Query   */
SELECT * FROM G1_CUSTOMER WHERE G1_CUST_ID IN (SELECT G1_CUST_ID FROM 
G1_VEHICLE GROUP BY (G1_CUST_ID) HAVING COUNT(G1_VEHICLE_ID) >=2 AND 
G1_CUST_ID IN (SELECT G1_CUST_ID FROM G1_PREMIUM WHERE 
G1_PREMIUM_PAYMENT_STATUS = 'NOT PAID') AND 
G1_CUST_ID IN(SELECT G1_CUST_ID FROM G1_INCIDENT_REPORT));

/*   Fifth Query   */
SELECT T1.* FROM G1_VEHICLE AS T1, G1_CUSTOMER AS T2, G1_PREMIUM AS T3 
WHERE T1.G1_CUST_ID = T2.G1_CUST_ID AND T2.G1_CUST_ID = T3.G1_CUST_ID AND 
T3.G1_PREMIUM_PAYMENT_AMOUNT > T1.G1_VEHICLE_REGISTRATION_NUMBER;

/*   Sixth Query   */
SELECT C.G1_CUST_FNAME, C.G1_CUST_LNAME FROM (G1_CUSTOMER C INNER JOIN 
G1_SETTLEMENT S ON S.G1_CUST_ID = C.G1_CUST_ID INNER JOIN G1_CLAIM Cl ON 
(Cl.G1_CLAIM_ID = S.G1_CLAIM_ID) INNER JOIN G1_TERMS_CONDITIONS T ON 
(T.G1_COVERAGE_ID = S.G1_COVERAGE_ID AND Cl.G1_CLAIM_AMOUNT < 
T.G1_COVERAGE_AMOUNT AND Cl.G1_CLAIM_AMOUNT > (S.G1_CLAIM_SETTLEMENT_ID + 
S.G1_VEHICLE_ID + S.G1_CLAIM_ID + S.G1_CUST_ID))); 